{
  "formatVersion": "1.1",
  "component": {
    "group": "org.twitter4j",
    "module": "twitter4j-media-support",
    "version": "4.0.8-20221004",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "twitter4j-media-support-4.0.8-20221004.jar",
          "url": "twitter4j-media-support-4.0.8-20221004.jar",
          "size": 261,
          "sha512": "25845676fa30c992e2aac77f24a1a6b08f099700baef1c0def32511ad6a8981e83c2882c7f5bbc92e11f61a10eff8c7f50347f1a3675f074ffdc8b659cfecfb5",
          "sha256": "be9717318fce82f856724b49341791678ddec455beb1e30b0a15d6ae600a5cb2",
          "sha1": "faa8634673c9f1777c664f14967a2ddc6a26a073",
          "md5": "75038eb39e5a392514fe1b1521fd3325"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.twitter4j",
          "module": "twitter4j-core",
          "version": {
            "requires": "4.0.8-20221004"
          }
        }
      ],
      "files": [
        {
          "name": "twitter4j-media-support-4.0.8-20221004.jar",
          "url": "twitter4j-media-support-4.0.8-20221004.jar",
          "size": 261,
          "sha512": "25845676fa30c992e2aac77f24a1a6b08f099700baef1c0def32511ad6a8981e83c2882c7f5bbc92e11f61a10eff8c7f50347f1a3675f074ffdc8b659cfecfb5",
          "sha256": "be9717318fce82f856724b49341791678ddec455beb1e30b0a15d6ae600a5cb2",
          "sha1": "faa8634673c9f1777c664f14967a2ddc6a26a073",
          "md5": "75038eb39e5a392514fe1b1521fd3325"
        }
      ]
    }
  ]
}
