{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.takke.mfm_kt",
    "module": "mfm_kt",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "mfm_kt-1.0.2.jar",
          "url": "mfm_kt-1.0.2.jar",
          "size": 8078,
          "sha512": "7c278bb8762630f827839687c448f4d1570368ecae52f1e8ce9f9a6da33c4e064f952aa8f0370aa97aa60bd2ffefa3b7b65a576e8a4d5d8f9751ca8cecd22e7a",
          "sha256": "1ce197d2f611d3405b53435f87199283291fc72542ea77e6c0debce37427afb7",
          "sha1": "67160a951a7d8ca06565ad8e0005fd0bd8c4b83f",
          "md5": "b3f5215257e543364ef827d5c56b7dc1"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "mfm_kt-1.0.2-sources.jar",
          "url": "mfm_kt-1.0.2-sources.jar",
          "size": 13864,
          "sha512": "61ca7b965048929e92bd8f16fe4ddc09f5f4c7d7e02a68dc16a63b93a7c9b2f853a58b4124e95c4dfd4732b8d7cc2f7a879c042ff61e05b647cb9d7823000fff",
          "sha256": "3f3e54ec978bed420d2a5c32fc2e26bd9125b1bd5f69ed835daac85a9f1b8343",
          "sha1": "1151d29e38017ed9171366982a92a9fc2427efc0",
          "md5": "fc057723e016729d407ac78c27372233"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mfm_kt-iosarm64/1.0.2/mfm_kt-iosarm64-1.0.2.module",
        "group": "jp.takke.mfm_kt",
        "module": "mfm_kt-iosarm64",
        "version": "1.0.2"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mfm_kt-iosarm64/1.0.2/mfm_kt-iosarm64-1.0.2.module",
        "group": "jp.takke.mfm_kt",
        "module": "mfm_kt-iosarm64",
        "version": "1.0.2"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mfm_kt-iosarm64/1.0.2/mfm_kt-iosarm64-1.0.2.module",
        "group": "jp.takke.mfm_kt",
        "module": "mfm_kt-iosarm64",
        "version": "1.0.2"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mfm_kt-iossimulatorarm64/1.0.2/mfm_kt-iossimulatorarm64-1.0.2.module",
        "group": "jp.takke.mfm_kt",
        "module": "mfm_kt-iossimulatorarm64",
        "version": "1.0.2"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mfm_kt-iossimulatorarm64/1.0.2/mfm_kt-iossimulatorarm64-1.0.2.module",
        "group": "jp.takke.mfm_kt",
        "module": "mfm_kt-iossimulatorarm64",
        "version": "1.0.2"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mfm_kt-iossimulatorarm64/1.0.2/mfm_kt-iossimulatorarm64-1.0.2.module",
        "group": "jp.takke.mfm_kt",
        "module": "mfm_kt-iossimulatorarm64",
        "version": "1.0.2"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mfm_kt-iosx64/1.0.2/mfm_kt-iosx64-1.0.2.module",
        "group": "jp.takke.mfm_kt",
        "module": "mfm_kt-iosx64",
        "version": "1.0.2"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mfm_kt-iosx64/1.0.2/mfm_kt-iosx64-1.0.2.module",
        "group": "jp.takke.mfm_kt",
        "module": "mfm_kt-iosx64",
        "version": "1.0.2"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mfm_kt-iosx64/1.0.2/mfm_kt-iosx64-1.0.2.module",
        "group": "jp.takke.mfm_kt",
        "module": "mfm_kt-iosx64",
        "version": "1.0.2"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../mfm_kt-jvm/1.0.2/mfm_kt-jvm-1.0.2.module",
        "group": "jp.takke.mfm_kt",
        "module": "mfm_kt-jvm",
        "version": "1.0.2"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../mfm_kt-jvm/1.0.2/mfm_kt-jvm-1.0.2.module",
        "group": "jp.takke.mfm_kt",
        "module": "mfm_kt-jvm",
        "version": "1.0.2"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../mfm_kt-jvm/1.0.2/mfm_kt-jvm-1.0.2.module",
        "group": "jp.takke.mfm_kt",
        "module": "mfm_kt-jvm",
        "version": "1.0.2"
      }
    }
  ]
}
