{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.takke.twitter4j-v2",
    "module": "twitter4j-v2-support-java-example",
    "version": "0.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "jbynbdfmr5dv3paf67pu7glnmi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "twitter4j-v2-support-java-example-0.3.1.jar",
          "url": "twitter4j-v2-support-java-example-0.3.1.jar",
          "size": 2068,
          "sha512": "67604f97e9f07ef312c6e14dc96362f8a8e2c953655bcca94ca74b6f655a345bd3063ea91b42c89557871ce153c734cdceba32825ea38884099e6b7529d20ca7",
          "sha256": "518dbf8a8a4f6c603ed5ef221f80fe62d85695912c4da71dc8e829caa389ecbb",
          "sha1": "35964646c2d8e0c6a6c733260e7f3dce265ae23b",
          "md5": "f83877edbdb8c6393244187eb044d153"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.twitter4j",
          "module": "twitter4j-core",
          "version": {
            "requires": "4.0.7"
          }
        },
        {
          "group": "jp.takke.twitter4j-v2",
          "module": "twitter4j-v2-support",
          "version": {
            "requires": "0.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "twitter4j-v2-support-java-example-0.3.1.jar",
          "url": "twitter4j-v2-support-java-example-0.3.1.jar",
          "size": 2068,
          "sha512": "67604f97e9f07ef312c6e14dc96362f8a8e2c953655bcca94ca74b6f655a345bd3063ea91b42c89557871ce153c734cdceba32825ea38884099e6b7529d20ca7",
          "sha256": "518dbf8a8a4f6c603ed5ef221f80fe62d85695912c4da71dc8e829caa389ecbb",
          "sha1": "35964646c2d8e0c6a6c733260e7f3dce265ae23b",
          "md5": "f83877edbdb8c6393244187eb044d153"
        }
      ]
    }
  ]
}
