{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.takke.twitter4j-v2",
    "module": "twitter4j-v2-support-kotlin-example",
    "version": "0.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "jqglqv3vinfjhlbe7hlxivmxze"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "twitter4j-v2-support-kotlin-example-0.2.1.jar",
          "url": "twitter4j-v2-support-kotlin-example-0.2.1.jar",
          "size": 8498,
          "sha512": "390c0cba1519cdeaaf66834cf16f3f3afa35e35f1aa9b7b3f0a01eb4d0a401b7c22b53b67389f92adab4502c36651e79e03e65e3773dc1d9154afa9eab7398db",
          "sha256": "c1b447f470c59ba65545992009ef9d79629198d85c6469c050b68059b847c2b1",
          "sha1": "def246af5b18b9c56e94451b829943979cef8efc",
          "md5": "cc3ad50255a7163a6a4848ef0a5dff12"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.twitter4j",
          "module": "twitter4j-core",
          "version": {
            "requires": "4.0.7"
          }
        },
        {
          "group": "jp.takke.twitter4j-v2",
          "module": "twitter4j-v2-support",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.5.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "twitter4j-v2-support-kotlin-example-0.2.1.jar",
          "url": "twitter4j-v2-support-kotlin-example-0.2.1.jar",
          "size": 8498,
          "sha512": "390c0cba1519cdeaaf66834cf16f3f3afa35e35f1aa9b7b3f0a01eb4d0a401b7c22b53b67389f92adab4502c36651e79e03e65e3773dc1d9154afa9eab7398db",
          "sha256": "c1b447f470c59ba65545992009ef9d79629198d85c6469c050b68059b847c2b1",
          "sha1": "def246af5b18b9c56e94451b829943979cef8efc",
          "md5": "cc3ad50255a7163a6a4848ef0a5dff12"
        }
      ]
    }
  ]
}
