{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.takke.twitter4j-v2",
    "module": "twitter4j-v2-support",
    "version": "0.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "jbynbdfmr5dv3paf67pu7glnmi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "twitter4j-v2-support-0.3.1.jar",
          "url": "twitter4j-v2-support-0.3.1.jar",
          "size": 119517,
          "sha512": "aeaafdc06d1d131c0eb659528beef330f6fb511146270908104387b4ae00d4576e3291fa6d2105901aa7114a529d94f2b6c8983990abd370aa66fb99678d0166",
          "sha256": "c5a4b05a00a16f2f352aa45601be9b07562fa95806073c0af83b95d2bdabd933",
          "sha1": "f17bdd54876270d943bb06e241e0cda6b0cd521e",
          "md5": "480224b3511fec342baa190c4c96ca44"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.twitter4j",
          "module": "twitter4j-core",
          "version": {
            "requires": "4.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.5.30"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "twitter4j-v2-support-0.3.1.jar",
          "url": "twitter4j-v2-support-0.3.1.jar",
          "size": 119517,
          "sha512": "aeaafdc06d1d131c0eb659528beef330f6fb511146270908104387b4ae00d4576e3291fa6d2105901aa7114a529d94f2b6c8983990abd370aa66fb99678d0166",
          "sha256": "c5a4b05a00a16f2f352aa45601be9b07562fa95806073c0af83b95d2bdabd933",
          "sha1": "f17bdd54876270d943bb06e241e0cda6b0cd521e",
          "md5": "480224b3511fec342baa190c4c96ca44"
        }
      ]
    }
  ]
}
