{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.takke.twitter4j-v2",
    "module": "twitter4j-v2-support-java-example",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "twitter4j-v2-support-java-example-1.0.0.jar",
          "url": "twitter4j-v2-support-java-example-1.0.0.jar",
          "size": 2068,
          "sha512": "688a02d0bff516eac2db4bf8b007332238de5c38e33abf5acfd059019de49f09c0f85fbbf4c7f8225431a97c41dd651994909fcba441e474b07d61211d308bac",
          "sha256": "179040bf8462b386036823d6a856eda8618c555debd8e26dca81e9e09e0780ea",
          "sha1": "24e80f45cb8b93b58cd989ebe5b746a8d2ae442b",
          "md5": "04005a18aea57d06252fc6a950de481f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.twitter4j",
          "module": "twitter4j-core",
          "version": {
            "requires": "4.0.7"
          }
        },
        {
          "group": "jp.takke.twitter4j-v2",
          "module": "twitter4j-v2-support",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "twitter4j-v2-support-java-example-1.0.0.jar",
          "url": "twitter4j-v2-support-java-example-1.0.0.jar",
          "size": 2068,
          "sha512": "688a02d0bff516eac2db4bf8b007332238de5c38e33abf5acfd059019de49f09c0f85fbbf4c7f8225431a97c41dd651994909fcba441e474b07d61211d308bac",
          "sha256": "179040bf8462b386036823d6a856eda8618c555debd8e26dca81e9e09e0780ea",
          "sha1": "24e80f45cb8b93b58cd989ebe5b746a8d2ae442b",
          "md5": "04005a18aea57d06252fc6a950de481f"
        }
      ]
    }
  ]
}
