{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.takke.twitter4j-v2",
    "module": "twitter4j-v2-support",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "twitter4j-v2-support-1.0.3.jar",
          "url": "twitter4j-v2-support-1.0.3.jar",
          "size": 133235,
          "sha512": "9ad023eda09eeed7124eb90fbcefd616898329dc83f17a58b63c742fd1c560a856da4afc0a7a782c222fa964cb2932b1cdec29301d26419a689a28038d556335",
          "sha256": "e83338c01cdc00fbd493e8e8b2a83823fdd05e9159aeb19f1367afc1ec1b7506",
          "sha1": "691f780c4d9adb838dc36761ef5d9ae417e018f5",
          "md5": "ed9a176f3b60666dd35bb83c28146ae1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.twitter4j",
          "module": "twitter4j-core",
          "version": {
            "requires": "4.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.6.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "twitter4j-v2-support-1.0.3.jar",
          "url": "twitter4j-v2-support-1.0.3.jar",
          "size": 133235,
          "sha512": "9ad023eda09eeed7124eb90fbcefd616898329dc83f17a58b63c742fd1c560a856da4afc0a7a782c222fa964cb2932b1cdec29301d26419a689a28038d556335",
          "sha256": "e83338c01cdc00fbd493e8e8b2a83823fdd05e9159aeb19f1367afc1ec1b7506",
          "sha1": "691f780c4d9adb838dc36761ef5d9ae417e018f5",
          "md5": "ed9a176f3b60666dd35bb83c28146ae1"
        }
      ]
    }
  ]
}
