{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mastodon4j-core/3.0.0-20260908/mastodon4j-core-3.0.0-20260908.module",
    "group": "com.sys1yagi",
    "module": "mastodon4j-core",
    "version": "3.0.0-20260908",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-android.jar",
          "url": "mastodon4j-core-android-3.0.0-20260908.jar",
          "size": 918655,
          "sha512": "0b76795aebc07e6482998c845e48e325d1729dd8cc0d45672b93d7f3ad1663e7a042d54252bcc32073fd3f4b9517c6f88859ea7af91b6c7a9dd02283b98797d7",
          "sha256": "fefe226855a5dde37466d2bcd3ae4c825febd674e9fc5adef4f81f9810416ca8",
          "sha1": "b42fc5d48704980c5a3e54642745f32e2e163c21",
          "md5": "33e7b270219baaff86fc191e227f910a"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-websockets",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-android.jar",
          "url": "mastodon4j-core-android-3.0.0-20260908.jar",
          "size": 918655,
          "sha512": "0b76795aebc07e6482998c845e48e325d1729dd8cc0d45672b93d7f3ad1663e7a042d54252bcc32073fd3f4b9517c6f88859ea7af91b6c7a9dd02283b98797d7",
          "sha256": "fefe226855a5dde37466d2bcd3ae4c825febd674e9fc5adef4f81f9810416ca8",
          "sha1": "b42fc5d48704980c5a3e54642745f32e2e163c21",
          "md5": "33e7b270219baaff86fc191e227f910a"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "core-android-sources.jar",
          "url": "mastodon4j-core-android-3.0.0-20260908-sources.jar",
          "size": 66817,
          "sha512": "639450d91344f5d3cc1d6238adff96aff2ec434be29c1315305b4032afb4d44a51652b7120ed19ceca6b9f769330dc9fc4ab3368ae8f4b16640c849f08dce104",
          "sha256": "fa6961697679b26d7b0b6c512af2b1c13507da556e5bbc96694f348e85fc5119",
          "sha1": "99eb0862ab7229d2600fa400265e7ec789f484e7",
          "md5": "2b567d6b3b3a9e885ca9e562d25faf44"
        }
      ]
    }
  ]
}
