{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.takke.twitter4j-v2",
    "module": "twitter4j-v2-support-kotlin-example",
    "version": "0.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "jbynbdfmr5dv3paf67pu7glnmi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "twitter4j-v2-support-kotlin-example-0.3.1.jar",
          "url": "twitter4j-v2-support-kotlin-example-0.3.1.jar",
          "size": 38306,
          "sha512": "53dbfc54cd563ddd2ebcc1d6c0e929514799cae671bb7e07cc06c3189ca5e3e6432083e9f0c22f92a684ba599600cf97f67512b80446744eb8d528f6a30dfd41",
          "sha256": "cc19670548bd700bb5dcddfc3ab7dffc3ad0c31f352e3852acebf3ca5927e39b",
          "sha1": "b89d66146707c1fcc5ae1a39c615c8a4a05b48cc",
          "md5": "28b3035a47dd9a4389c415f7174c12a9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.twitter4j",
          "module": "twitter4j-core",
          "version": {
            "requires": "4.0.7"
          }
        },
        {
          "group": "jp.takke.twitter4j-v2",
          "module": "twitter4j-v2-support",
          "version": {
            "requires": "0.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.5.30"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "twitter4j-v2-support-kotlin-example-0.3.1.jar",
          "url": "twitter4j-v2-support-kotlin-example-0.3.1.jar",
          "size": 38306,
          "sha512": "53dbfc54cd563ddd2ebcc1d6c0e929514799cae671bb7e07cc06c3189ca5e3e6432083e9f0c22f92a684ba599600cf97f67512b80446744eb8d528f6a30dfd41",
          "sha256": "cc19670548bd700bb5dcddfc3ab7dffc3ad0c31f352e3852acebf3ca5927e39b",
          "sha1": "b89d66146707c1fcc5ae1a39c615c8a4a05b48cc",
          "md5": "28b3035a47dd9a4389c415f7174c12a9"
        }
      ]
    }
  ]
}
