{
  "formatVersion": "1.1",
  "component": {
    "url": "../../twitter4j-v2-support/2.0.0-20260908/twitter4j-v2-support-2.0.0-20260908.module",
    "group": "io.github.takke",
    "module": "twitter4j-v2-support",
    "version": "2.0.0-20260908",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.twitter4j",
          "module": "twitter4j-core",
          "version": {
            "requires": "4.1.0-20260908"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "twitter4j-v2-support-android-2.0.0-20260908.jar",
          "url": "jp.takke.twitter4j-v2-2.0.0-20260908.jar",
          "size": 161013,
          "sha512": "2f4f494f29be2f1f75e8b95cae058fea9d457ae66677f8af99c8786ee8a3941c596a40d87e4da71a300c9324c576be30099fa160923f0b830922291605c9b1b2",
          "sha256": "730bb829cfdad4c5f23c22f7ce2a499888eecd2b641f26ac8e88e1be0925a860",
          "sha1": "b31f1422ac40236a9889769d1dad3925829d6b07",
          "md5": "4a2609cde2b6b2afcd5e593e6d636eae"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.twitter4j",
          "module": "twitter4j-core",
          "version": {
            "requires": "4.1.0-20260908"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "twitter4j-v2-support-android-2.0.0-20260908.jar",
          "url": "jp.takke.twitter4j-v2-2.0.0-20260908.jar",
          "size": 161013,
          "sha512": "2f4f494f29be2f1f75e8b95cae058fea9d457ae66677f8af99c8786ee8a3941c596a40d87e4da71a300c9324c576be30099fa160923f0b830922291605c9b1b2",
          "sha256": "730bb829cfdad4c5f23c22f7ce2a499888eecd2b641f26ac8e88e1be0925a860",
          "sha1": "b31f1422ac40236a9889769d1dad3925829d6b07",
          "md5": "4a2609cde2b6b2afcd5e593e6d636eae"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "twitter4j-v2-support-android-2.0.0-20260908-sources.jar",
          "url": "jp.takke.twitter4j-v2-2.0.0-20260908-sources.jar",
          "size": 37956,
          "sha512": "dbb4292c9d00f4409ed076f94990e70234fa2d0f0a97fe51e90b71efc7aa502fda8b741128cc7dcdd442d440163c36d78c8e90faf307b65f00dc91c1809bea69",
          "sha256": "c176c15cf92706fb4e5a386753e57b707229c37e62d3fc0342e4506e4d902a57",
          "sha1": "4197da1996076009a0c1e9f67d286ec516066d13",
          "md5": "fbc4a17d25ff0f8526e81211f3408d6d"
        }
      ]
    }
  ]
}
