{
  "formatVersion": "1.1",
  "component": {
    "group": "org.twitter4j",
    "module": "twitter4j-media-support",
    "version": "4.0.8-20210512",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "x4daq4wxxrhu7bpx4xmikkt7dy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 6,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "twitter4j-media-support-4.0.8-20210512.jar",
          "url": "twitter4j-media-support-4.0.8-20210512.jar",
          "size": 261,
          "sha512": "64a619dfd22cbf5a8afbb5b70791cdc3fe5e52d5ef9dc159e70da8cb72e9cb27de04e44574495b713fbe4b452ee55b820a9f6f01a8ce0193e3cdc1f1c8e3f923",
          "sha256": "eb68248c1ac645dd19c1a7dafa9f68cbd8e441ec95c33c047c7b985c4b706a85",
          "sha1": "8985b378a50f8252ad2a7b657d05db75c1cefde8",
          "md5": "ad920d780761526ba53ebbc3a885409f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 6,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.twitter4j",
          "module": "twitter4j-core",
          "version": {
            "requires": "4.0.8-20210512"
          }
        }
      ],
      "files": [
        {
          "name": "twitter4j-media-support-4.0.8-20210512.jar",
          "url": "twitter4j-media-support-4.0.8-20210512.jar",
          "size": 261,
          "sha512": "64a619dfd22cbf5a8afbb5b70791cdc3fe5e52d5ef9dc159e70da8cb72e9cb27de04e44574495b713fbe4b452ee55b820a9f6f01a8ce0193e3cdc1f1c8e3f923",
          "sha256": "eb68248c1ac645dd19c1a7dafa9f68cbd8e441ec95c33c047c7b985c4b706a85",
          "sha1": "8985b378a50f8252ad2a7b657d05db75c1cefde8",
          "md5": "ad920d780761526ba53ebbc3a885409f"
        }
      ]
    }
  ]
}
