{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.takke.twitter4j-v2",
    "module": "twitter4j-v2-support-java-example",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "bye5jnt5qbexxftakwiyvd7n2m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "twitter4j-v2-support-java-example-0.2.0.jar",
          "url": "twitter4j-v2-support-java-example-0.2.0.jar",
          "size": 2068,
          "sha512": "5527d06fb805de026ad6d22d1ae0d010df5fcae980fd99e23f658007ddc3004c3b219f7f6161bd2270ff9192564b8e104f9509b2e1050caabf6222bfac65ec3e",
          "sha256": "370bbf13d0deea2cf7fa637a6919e31ccf66e86b36fe6058fc2de58738011586",
          "sha1": "9887e0cdf848c08d1bc6f4888d5f633aa5b7885c",
          "md5": "9943b1b083d5f5e5f8617999d6ff1263"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.twitter4j",
          "module": "twitter4j-core",
          "version": {
            "requires": "4.0.7"
          }
        },
        {
          "group": "jp.takke.twitter4j-v2",
          "module": "twitter4j-v2-support",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "twitter4j-v2-support-java-example-0.2.0.jar",
          "url": "twitter4j-v2-support-java-example-0.2.0.jar",
          "size": 2068,
          "sha512": "5527d06fb805de026ad6d22d1ae0d010df5fcae980fd99e23f658007ddc3004c3b219f7f6161bd2270ff9192564b8e104f9509b2e1050caabf6222bfac65ec3e",
          "sha256": "370bbf13d0deea2cf7fa637a6919e31ccf66e86b36fe6058fc2de58738011586",
          "sha1": "9887e0cdf848c08d1bc6f4888d5f633aa5b7885c",
          "md5": "9943b1b083d5f5e5f8617999d6ff1263"
        }
      ]
    }
  ]
}
