{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.takke.twitter4j-v2",
    "module": "twitter4j-v2-support",
    "version": "1.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "twitter4j-v2-support-1.0.4.jar",
          "url": "twitter4j-v2-support-1.0.4.jar",
          "size": 133199,
          "sha512": "67431d7936aa7414b2796e41f95fcd1c4c87309f2b123b7be4c26b46c61cf2f21d43b51b4fdd640569ad1efcd005618f93c7dc4ce87c97e0d2df1dfc3e2d5afc",
          "sha256": "7b6658d74f74c571245be4cd6f4ef93aefaffa8bdf23c73607c2a76f7b8614ea",
          "sha1": "324db0102c29b11180f40a26053758c93c0d1299",
          "md5": "f37851aeb2b22ae07926d5abdcbc0476"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.twitter4j",
          "module": "twitter4j-core",
          "version": {
            "requires": "4.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.6.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "twitter4j-v2-support-1.0.4.jar",
          "url": "twitter4j-v2-support-1.0.4.jar",
          "size": 133199,
          "sha512": "67431d7936aa7414b2796e41f95fcd1c4c87309f2b123b7be4c26b46c61cf2f21d43b51b4fdd640569ad1efcd005618f93c7dc4ce87c97e0d2df1dfc3e2d5afc",
          "sha256": "7b6658d74f74c571245be4cd6f4ef93aefaffa8bdf23c73607c2a76f7b8614ea",
          "sha1": "324db0102c29b11180f40a26053758c93c0d1299",
          "md5": "f37851aeb2b22ae07926d5abdcbc0476"
        }
      ]
    }
  ]
}
