{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.takke.twitter4j-v2",
    "module": "twitter4j-v2-support",
    "version": "0.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "jqglqv3vinfjhlbe7hlxivmxze"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "twitter4j-v2-support-0.2.1.jar",
          "url": "twitter4j-v2-support-0.2.1.jar",
          "size": 60303,
          "sha512": "aa6981d5877dbb522a0e59f92e44306ba9ff380e310a0f4db7af428a27ed778c948d9332c24e7003e63dbd5cf98d3607182c59cd92862c0442f8084367869bad",
          "sha256": "f1b520f11f6b2424b05d2913ff01224fc900bf28694dec1dd5cd15b1d6a21625",
          "sha1": "45010fdd16b429bad171eafaf04c593b1491cce2",
          "md5": "319b07d745d394e5d8a910a76c0d0d13"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.twitter4j",
          "module": "twitter4j-core",
          "version": {
            "requires": "4.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.5.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "twitter4j-v2-support-0.2.1.jar",
          "url": "twitter4j-v2-support-0.2.1.jar",
          "size": 60303,
          "sha512": "aa6981d5877dbb522a0e59f92e44306ba9ff380e310a0f4db7af428a27ed778c948d9332c24e7003e63dbd5cf98d3607182c59cd92862c0442f8084367869bad",
          "sha256": "f1b520f11f6b2424b05d2913ff01224fc900bf28694dec1dd5cd15b1d6a21625",
          "sha1": "45010fdd16b429bad171eafaf04c593b1491cce2",
          "md5": "319b07d745d394e5d8a910a76c0d0d13"
        }
      ]
    }
  ]
}
