{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.takke.twitter4j-v2",
    "module": "twitter4j-v2-support-java-example",
    "version": "0.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "jqglqv3vinfjhlbe7hlxivmxze"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "twitter4j-v2-support-java-example-0.2.1.jar",
          "url": "twitter4j-v2-support-java-example-0.2.1.jar",
          "size": 2068,
          "sha512": "bfda5d5ebf55329d3f5d4a7af5501585a5a37ff31b124a5a2e746a3e25376f2cc12adeae82ed447254bc05b38266ff321ab0bd7a73ffcdf4cea70a896184a610",
          "sha256": "c73c2181287a2df8f535758a390ca2ddeee48d202bce3148640af54c1b367c9a",
          "sha1": "0ba80ca91cf305eaded8ebe04ef1ccf7c4ba9f5d",
          "md5": "cf0f3178a48fc22f1b8b33e30678c486"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.twitter4j",
          "module": "twitter4j-core",
          "version": {
            "requires": "4.0.7"
          }
        },
        {
          "group": "jp.takke.twitter4j-v2",
          "module": "twitter4j-v2-support",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "twitter4j-v2-support-java-example-0.2.1.jar",
          "url": "twitter4j-v2-support-java-example-0.2.1.jar",
          "size": 2068,
          "sha512": "bfda5d5ebf55329d3f5d4a7af5501585a5a37ff31b124a5a2e746a3e25376f2cc12adeae82ed447254bc05b38266ff321ab0bd7a73ffcdf4cea70a896184a610",
          "sha256": "c73c2181287a2df8f535758a390ca2ddeee48d202bce3148640af54c1b367c9a",
          "sha1": "0ba80ca91cf305eaded8ebe04ef1ccf7c4ba9f5d",
          "md5": "cf0f3178a48fc22f1b8b33e30678c486"
        }
      ]
    }
  ]
}
