{
  "formatVersion": "1.1",
  "component": {
    "group": "org.twitter4j",
    "module": "twitter4j-http2-support",
    "version": "4.1.0-20260908",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "twitter4j-http2-support-4.1.0-20260908.jar",
          "url": "twitter4j-http2-support-4.1.0-20260908.jar",
          "size": 15581,
          "sha512": "de41ca27920127e5a83a8f49452859185eae3bae745784b1a74b3c3237edb2761325909d4a7b5b1097fda40c08e20df7ecba5e363929613cb0dd7a306f02589e",
          "sha256": "3db4d2a8e44c738c47680cd7080a49ad239ea7bf708ed6ef23087b2606a76f8b",
          "sha1": "12615e8d12ecf0a2b31e2101b491a13cf71656a3",
          "md5": "9a497c2538169b3f63687d8338e24a46"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.twitter4j",
          "module": "twitter4j-core",
          "version": {
            "requires": "4.1.0-20260908"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "twitter4j-http2-support-4.1.0-20260908.jar",
          "url": "twitter4j-http2-support-4.1.0-20260908.jar",
          "size": 15581,
          "sha512": "de41ca27920127e5a83a8f49452859185eae3bae745784b1a74b3c3237edb2761325909d4a7b5b1097fda40c08e20df7ecba5e363929613cb0dd7a306f02589e",
          "sha256": "3db4d2a8e44c738c47680cd7080a49ad239ea7bf708ed6ef23087b2606a76f8b",
          "sha1": "12615e8d12ecf0a2b31e2101b491a13cf71656a3",
          "md5": "9a497c2538169b3f63687d8338e24a46"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "twitter4j-http2-support-4.1.0-20260908-sources.jar",
          "url": "twitter4j-http2-support-4.1.0-20260908-sources.jar",
          "size": 9758,
          "sha512": "b92bf2f7f0a815bbe94bb2e72119cad5492cdb7e479bff263c5805cc0867b9117d0c85eecb9ff4ef167db5d7eabc4af973264efd3f6108dc5ea88cbb3ad466ab",
          "sha256": "ed3606bf5617f34a908c84a5564a50599eefa6943e51daab5d08ab12cad5f527",
          "sha1": "c3af8b81a8fba960734ccb2ead90bb3547f7e0a5",
          "md5": "805161dae5d57dd36a4eafda105065fa"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "twitter4j-http2-support-4.1.0-20260908-javadoc.jar",
          "url": "twitter4j-http2-support-4.1.0-20260908-javadoc.jar",
          "size": 325731,
          "sha512": "676b52dff17ae8d98e6b36425371a2d300d8723b7529eb11b3d5986fbb65735ac65230467fd7e6d28f7d776f0c29f6186c37bda4784b729ef6793e01da2e15fd",
          "sha256": "ca4e655bb4090956a78486d0a9cd3fbd053884e3a80fd07dba6f03354b007f60",
          "sha1": "c90e2adcc65b84ac222c9d95981e756abaa37e88",
          "md5": "09631ffa061afdb0ab9a44679cfe7530"
        }
      ]
    }
  ]
}
