{
  "formatVersion": "1.1",
  "component": {
    "group": "org.twitter4j",
    "module": "twitter4j-http2-support",
    "version": "4.1.0-20260908",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "twitter4j-http2-support-4.1.0-20260908.jar",
          "url": "twitter4j-http2-support-4.1.0-20260908.jar",
          "size": 15581,
          "sha512": "ee7e62bcf222840ce15153a2616dcc1b9766f4ff9626557732e72f15b64e86d048e5c4fe892c2238a90f5ea952ffe39fdba91e5e6d62a67c047fee994b8e3650",
          "sha256": "2aa9d0423e8e64e2030676ad72bbac959c33a00c18a4996d8c47fea0753d3f5e",
          "sha1": "98a82bac9637314ae9349de964c58ad304efaadf",
          "md5": "858eb1c84f33547e5e2dc83f4acc97ec"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.twitter4j",
          "module": "twitter4j-core",
          "version": {
            "requires": "4.1.0-20260908"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "twitter4j-http2-support-4.1.0-20260908.jar",
          "url": "twitter4j-http2-support-4.1.0-20260908.jar",
          "size": 15581,
          "sha512": "ee7e62bcf222840ce15153a2616dcc1b9766f4ff9626557732e72f15b64e86d048e5c4fe892c2238a90f5ea952ffe39fdba91e5e6d62a67c047fee994b8e3650",
          "sha256": "2aa9d0423e8e64e2030676ad72bbac959c33a00c18a4996d8c47fea0753d3f5e",
          "sha1": "98a82bac9637314ae9349de964c58ad304efaadf",
          "md5": "858eb1c84f33547e5e2dc83f4acc97ec"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "twitter4j-http2-support-4.1.0-20260908-sources.jar",
          "url": "twitter4j-http2-support-4.1.0-20260908-sources.jar",
          "size": 9758,
          "sha512": "f3affd66105add78f765e59fc18017afc74c474801cd4f5d92fef9fb21b6256a1232150f7d9fd6af7ebe7445fc3ca2eebe3e486059c1c01a9eca141dae834eaf",
          "sha256": "84a17ae2021230a0ec836e5c92bf01c70551c1adff649d9041ad82711872c3e2",
          "sha1": "c89472e4432d19137c0493a20325bb65a4188a69",
          "md5": "a9f6faa260f645af19d3dff8a728936d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "twitter4j-http2-support-4.1.0-20260908-javadoc.jar",
          "url": "twitter4j-http2-support-4.1.0-20260908-javadoc.jar",
          "size": 325732,
          "sha512": "50aa7bf6b48d8476d7f26479a46171956c60a879e68219aa59987489014d0f26e43511490fd6b2629330fe8f34200b78252504df05e8fd7efeff407ddd9f7ca4",
          "sha256": "7d9be431294ceaab38082a721592d821dec550a71b865ff296099aa8e7cedc7b",
          "sha1": "ea5ea22584a283c7cc531e38581bf51e1b0c401a",
          "md5": "10b85615a065654acbfbedc6c6a5b853"
        }
      ]
    }
  ]
}
