{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mfm_kt/1.0.1/mfm_kt-1.0.1.module",
    "group": "jp.takke.mfm_kt",
    "module": "mfm_kt",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "mfm_kt-iosSimulatorArm64Main-1.0.1.klib",
          "url": "mfm_kt-iossimulatorarm64-1.0.1.klib",
          "size": 78426,
          "sha512": "76a406b77e752caaa93c36134b196dc63156baa17feb987ec25e252a35f0f24432ee79377b6ef70e15d59fa9d23307798a283330609dba7fea0328c15216912b",
          "sha256": "0533cf4a7233b3081905d73b98e85b015c0c95d43c528facb07f9361b9bee49d",
          "sha1": "e32cf641510ac9bc23de8a39a8879ae82fb6db50",
          "md5": "cca0cf9ef7254f8cfbc3f4fb819ab33a"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "mfm_kt-iossimulatorarm64-1.0.1-sources.jar",
          "url": "mfm_kt-iossimulatorarm64-1.0.1-sources.jar",
          "size": 13768,
          "sha512": "36d34193fbfe4d93f7c3d149239128e3fe46afccb6a288f29ba1ef15f8d975b17f2b26e5fb9ccb5a1608a14c42917746280169351855ec4b60f060b9bd36d987",
          "sha256": "e2a127c00d616458d39d44fa1f9290f8bfd951e6cb5800cadd67256fa1d66e35",
          "sha1": "8ea77e7008595cbd0e2f52b900614bf823a1d585",
          "md5": "cfd83cc2a853804dec7ede6a584cda8c"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "mfm_kt-iossimulatorarm64-1.0.1-metadata.jar",
          "url": "mfm_kt-iossimulatorarm64-1.0.1-metadata.jar",
          "size": 261,
          "sha512": "d4a7b05d4dcf92c7591d195634e10f630931b8c3688885802e5030f00d74ef87290e1791669649b626b98f4fa5be2aa145b36298d0e9d5ab8c87d2b6dab9164c",
          "sha256": "e7163db64e6b868443f07e1e0ff879f671a75bd981c69d4d334e1410df81a778",
          "sha1": "8f4977d576692d48b04512771430c12047185f45",
          "md5": "06a5994fea77ce245d98166b749b606a"
        }
      ]
    }
  ]
}
